services:
  db:
    image: "mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password123 --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 3s
      retries: 1000
      start_period: 300s
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./out/sql:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      - dapr-network

  server:
    build: "StateStore/Server/"
    depends_on:
      db:
          condition: service_healthy
      redis:
          condition: service_started
      placement:
          condition: service_started
    networks:
      - dapr-network
    ports:
      - "5000:5000"

  server-dapr:
    build: "StateStore/Server/dapr/"
    depends_on:
      - server
    network_mode: "service:server"
    networks:
      - dapr-network

  java-api:
    build: "Webapi/"
    depends_on:
      - server
      - redis
      - placement
    networks:
      - dapr-network
    ports:
      - "5001:5001"
      - "8080:8080"

  java-api-dapr:
    build: "Webapi/dapr/"
    depends_on:
      - java-api
    network_mode: "service:java-api"
    networks:
      - dapr-network

  react-frontend:
    build: "frontend/"
    depends_on:
      - java-api
    networks:
      - dapr-network
    ports:
      - 3000:80

  event-listener:
    build: StateStore/EventListener/
    depends_on:
      - server
      - redis
      - placement
    networks:
      - dapr-network

  event-listener-dapr:
    build: "StateStore/EventListener/dapr/"
    depends_on:
      - event-listener
    network_mode: "service:event-listener"
    networks:
      - dapr-network

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dapr-network

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - dapr-network

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./out/seq-data/:/data"
    networks:
      - dapr-network

networks:
    dapr-network: