services:
  db:
    image: "mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password123 --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 3s
      retries: 1000
      start_period: 300s
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./out/sql:/var/lib/mysql
    ports:
    - "3306:3306"

  backend:
    build: "Backend/"
    depends_on:
      - redis
      - placement
    ports:
      - "5001:5001"
      - "8080:8080"

  backend-dapr:
    build: "Backend/dapr/"
    depends_on:
      - backend
    network_mode: "service:backend"

  react-frontend:
    build: "Frontend/"
    depends_on:
      - backend
    ports:
      - 3000:80

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./out/seq-data/:/data"