services:
  oracle-db:
    image: "container-registry.oracle.com/database/express:latest"
    healthcheck:
      test: ["CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 1s
      timeout: 3s
      retries: 1000
      start_period: 300s
    environment:
      ORACLE_PWD: "password123"
    volumes:
      - ./oracle-data:/opt/oracle/oradata
    ports:
    - "1521:1521"
    - "5500:5500"
    networks:
      - dapr-network

  server:
    build: ./Server/
    depends_on:
      oracle-db:
          condition: service_healthy
      redis:
          condition: service_started
      placement:
          condition: service_started

    networks:
      - dapr-network
    ports:
      - "5000:5000"

  server-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd", "-app-id", "server", "--app-port", "3000","-placement-host-address", "placement:50006","-components-path", "/components", "--config", "/dapr/config.yaml", "--log-level", "debug"]
    volumes:
      - "./Server/dapr:/dapr"
      - "./Server/dapr/components/:/components"
    depends_on:
      server:
          condition: service_started
    network_mode: "service:server"
    networks:
      - dapr-network

  java-api:
    build: ./java/
    depends_on:
      oracle-db:
        condition: service_healthy
      server:
          condition: service_started
      redis:
          condition: service_started
      placement:
          condition: service_started
    networks:
      - dapr-network
    ports:
      - "5001:5001"

  java-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd", "-app-id", "java-api", "--app-port", "3002","-placement-host-address", "placement:50006","-components-path", "/components", "--config", "/dapr/config.yaml", "--log-level", "debug"]
    volumes:
      - "./java/dapr:/dapr"
      - "./java/dapr/components/:/components"
    depends_on:
      - java-api
    network_mode: "service:java-api"
    networks:
      - dapr-network

  event-listener:
    build: ./EventListener/
    depends_on:
      - server
      - redis
      - placement
    networks:
      - dapr-network

  event-listener-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd", "-app-id", "event-listener", "--app-port", "3001","-placement-host-address", "placement:50006","-components-path", "/components", "--config", "/dapr/config.yaml"]
    volumes:
      - "./EventListener/dapr/:/dapr"
      - "./EventListener/dapr/components/:/components"
    depends_on:
      - event-listener
    network_mode: "service:event-listener"
    networks:
      - dapr-network

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dapr-network

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - dapr-network

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./seq-data/:/data"
    networks:
      - dapr-network

networks:
    dapr-network: