apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s
    retries:
      retryForever:
        policy: exponential
        maxInterval: 1m
        maxRetries: -1 # retry indefinitely

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    components:
      sqlserver.statestore: 
        outbound:
          retry: retryForever
          timeout: important
          circuitBreaker: simpleCB