apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqlserver.statestore
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    #value: "server=sql;Data Source=sql;User ID=user;Password=password;Connect Timeout=60;Encrypt=False;MultiSubnetFailover=False"
    value: "user:password@tcp(sql:3306)/dapr?allowNativePasswords=true"