apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqlserver.statestore
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "root:password123@tcp(db:3306)/?allowNativePasswords=true"